export const data = [
    {
        id:1,
        ns:'Ace',
        suits:'Spades',
        value:1
    },
    {
        id:2,
        ns:'Ace',
        suits:'Hearts',
        value:1
    },
    {
        id:3,
        ns:'Ace',
        suits:'Diamonds',
        value:1
    },
    {
        id:4,
        ns:'Ace',
        suits:'Clubs',
        value:1
    },
    {
        id:5,
        ns:'Two',
        suits:'Spades',
        value:2
    },
    {
        id:6,
        ns:'Two',
        suits:'Hearts',
        value:2
    },
    {
        id:7,
        ns:'Two',
        suits:'Diamonds',
        value:2
    },
    {
        id:8,
        ns:'Two',
        suits:'Clubs',
        value:2
    },
    {
        id:9,
        ns:'Three',
        suits:'Spades',
        value:3
    },
    {
        id:10,
        ns:'Three',
        suits:'Hearts',
        value:3
    },
    {
        id:11,
        ns:'Three',
        suits:'Diamonds',
        value:3
    },
    {
        id:12,
        ns:'Three',
        suits:'Clubs',
        value:3
    },
    {
        id:13,
        ns:'Four',
        suits:'Spades',
        value:4
    },
    {
        id:14,
        ns:'Four',
        suits:'Hearts',
        value:4
    },
    {
        id:15,
        ns:'Four',
        suits:'Diamonds',
        value:4
    },
    {
        id:16,
        ns:'Four',
        suits:'Clubs',
        value:4
    },
    {
        id:17,
        ns:'Five',
        suits:'Spades',
        value:5
    },
    {
        id:18,
        ns:'Five',
        suits:'Hearts',
        value:5
    },
    {
        id:19,
        ns:'Five',
        suits:'Diamonds',
        value:5
    },
    {
        id:20,
        ns:'Five',
        suits:'Clubs',
        value:5
    },
    {
        id:21,
        ns:'Six',
        suits:'Spades',
        value:6
    },
    {
        id:22,
        ns:'Six',
        suits:'Hearts',
        value:6
    },
    {
        id:23,
        ns:'Six',
        suits:'Diamonds',
        value:6
    },
    {
        id:24,
        ns:'Six',
        suits:'Clubs',
        value:6
    },
    {
        id:25,
        ns:'Seven',
        suits:'Spades',
        value:7
    },
    {
        id:26,
        ns:'Seven',
        suits:'Hearts',
        value:7
    },
    {
        id:27,
        ns:'Seven',
        suits:'Diamonds',
        value:7
    },
    {
        id:28,
        ns:'Seven',
        suits:'Clubs',
        value:7
    },
    {
        id:29,
        ns:'Eight',
        suits:'Spades',
        value:8
    },
    {
        id:30,
        ns:'Eight',
        suits:'Hearts',
        value:8
    },
    {
        id:31,
        ns:'Eight',
        suits:'Diamonds',
        value:8
    },
    {
        id:32,
        ns:'Eight',
        suits:'Clubs',
        value:8
    },
    {
        id:33,
        ns:'Nine',
        suits:'Spades',
        value:9
    },
    {
        id:34,
        ns:'Nine',
        suits:'Hearts',
        value:9
    },
    {
        id:35,
        ns:'Nine',
        suits:'Diamonds',
        value:9
    },
    {
        id:36,
        ns:'Nine',
        suits:'Clubs',
        value:9
    },
    {
        id:37,
        ns:'Ten',
        suits:'Spades',
        value:10
    },
    {
        id:38,
        ns:'Ten',
        suits:'Hearts',
        value:10
    },
    {
        id:39,
        ns:'Ten',
        suits:'Diamonds',
        value:10
    },
    {
        id:40,
        ns:'Ten',
        suits:'Clubs',
        value:10
    },
    {
        id:41,
        ns:'Jack',
        suits:'Spades',
        value:10
    },
    {
        id:42,
        ns:'Jack',
        suits:'Hearts',
        value:10
    },
    {
        id:43,
        ns:'Jack',
        suits:'Diamonds',
        value:10
    },
    {
        id:44,
        ns:'Jack',
        suits:'Clubs',
        value:10
    },
    {
        id:45,
        ns:'Queen',
        suits:'Spades',
        value:10
    },
    {
        id:46,
        ns:'Queen',
        suits:'Hearts',
        value:10
    },
    {
        id:47,
        ns:'Queen',
        suits:'Diamonds',
        value:10
    },
    {
        id:48,
        ns:'Queen',
        suits:'Clubs',
        value:10
    },
    {
        id:49,
        ns:'King',
        suits:'Spades',
        value:10
    },
    {
        id:50,
        ns:'King',
        suits:'Hearts',
        value:10
    },
    {
        id:51,
        ns:'King',
        suits:'Diamonds',
        value:10
    },
    {
        id:52,
        ns:'King',
        suits:'Clubs',
        value:10
    },
]
